AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWSBot CloudFormation template: Creates a Lambda function and role for the RSSReader service.
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: function.zip
      Description: Lambda function for the RSSReader service
      FunctionName: RSSReader
      Handler: lambda_function.lambda_handler
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Runtime: python2.7
      MemorySize: '256'
      Timeout: '300'
  LambdaTrigger:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Trigger to invoke create action on the RSSReader Lambda function
      ScheduleExpression: cron(*/5 * * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt
            - LambdaFunction
            - Arn
          Id: RSSReader
          Input: '{"table_name": "aws-rss-whats-new", "rss_url": "https://aws.amazon.com/new/feed/"}'
  InvokeLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt
        - LambdaTrigger
        - Arn
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: '*'
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource: '*'